### ISSUE TITLE
[WARN] unsupported SOCKS version

### ISSUE THREAD

**Issue by geaplanet** [extremecoders-re/go-dispatch-proxy#11]
I'm trying go-dispatch-proxy in W10, but I got this meesages:

[WARN] unsupported SOCKS
[WARN] client connection request failed
[WARN] client greeting failed

What could be the problem?

![screenshot 10](https://user-images.githubusercontent.com/1422345/129862772-6272ad6b-44a5-450f-852e-e36a80880daa.png)
 version

**Comment by geaplanet** [comment]
Sorry, I had an stupid typing error.

**Comment by SirSAC** [comment]
Hi, can u tell me how set this IP:Port and where?

**Comment by geaplanet** [comment]
> 
> 
> Hi, can u tell me how set this IP:Port and where?

Open proxy settings and then active 127.0.0.1 with the port 8080

**Comment by SirSAC** [comment]
i was updated the qurstion to be more explicit

**Comment by geaplanet** [comment]
> 
> 
> Hi, can u tell me how set this IP:Port and where?
> The application work on browsers (u need an extension for Chrome based) and on Windows only if u have a software like Privoxy to can configure the http or https in Windows because Privoxy can do a proxy chain like working through go-dispatch-proxy.

It works with a windows only configuration, you don't need any chrome/firefox extension.

**Comment by SirSAC** [comment]
so u was configured on proxy settings from control panel?

**Comment by SirSAC** [comment]
anyway, can u want and can to test my upgraded version of go-dispatch-proxy and tell me who is better?
https://github.com/SirSAC/DisPro

**Comment by geaplanet** [comment]
> 
> 
> so u was configured on proxy settings from control panel?

Yes.
Have a look to the [old tutorial for the abandoned dispatch-proxy](https://imgur.com/a/0snis)

**Comment by geaplanet** [comment]
> 
> 
> anyway, can u want and can to test my upgraded version of go-dispatch-proxy and tell me who is better?
> https://github.com/SirSAC/DisPro

Of course.

**Comment by SirSAC** [comment]
> > so u was configured on proxy settings from control panel?
> 
> Yes.
> Have a look to the [old tutorial for the abandoned dispatch-proxy](https://imgur.com/a/0snis)

this version of software is not coming from me or extremecoders-re, is working on http or https so thats why it work without any browser or software but is slow and have some issues, and my and extremecoders-re software works on socks5.

**Comment by SirSAC** [comment]
btw, all credits to the extremecoders-re for the soft, i just fork this and make and upgraded version, anyway read instruction 
 from my soft be careful.

**Comment by gitzec** [comment]
Windows 11
Use proxy ip address: 
`socks5=<ip>`

![Screenshot 2023-12-08 163050](https://github.com/extremecoders-re/go-dispatch-proxy/assets/27860439/e2071704-cd41-4919-99e5-4a83ae826f7f)
