### ISSUE TITLE
Runing the proxy in hidden mode without a window

### ISSUE THREAD

**Issue by shraga100** [extremecoders-re/go-dispatch-proxy#16]
Hello,
Can you add a parameter that will run the proxy server in hidden mode, without an open window in the background?
Thanks

**Comment by extremecoders-re** [comment]
@shraga100 You can compile using the parameter `-H windowsgui`. ([Docs](https://pkg.go.dev/cmd/link))

```
go build -H windowsgui
```

This should generate a gui mode executable which doesn't open the console.
