### ISSUE TITLE
Artifacts deleted

### ISSUE THREAD

**Issue by sebelga** [extremecoders-re/go-dispatch-proxy#2]
Hi!

Any chance you could re-publish the artifacts? They have been deleted.

Cheers! 👍

**Comment by extremecoders-re** [comment]
Done!

In case, they are deleted in future, you can always get them from [releases](https://github.com/extremecoders-re/go-dispatch-proxy/releases)

**Comment by sebelga** [comment]
Awesome ! thanks very much. 👍
