### ISSUE TITLE
When Contention ratio is needed?

### ISSUE THREAD

**Issue by BEST8OY** [extremecoders-re/go-dispatch-proxy#20]
Hi 
When Contention ratio is needed?
I mean if for one connection is 3 and for other connection is 2
what's its effect on combined connection?
what's its difference with 1 ratio for each connection?

**Comment by extremecoders-re** [comment]
> _When Contention ratio is needed?_

Needed when you're combining two or more Internet connections with different bandwidths, like a 100 Mbit fiber uplink and a 10 Mbit ADSL uplink. You would want more connections to be routed over fiber than ADSL.

> _I mean if for one connection is 3 and for other connection is 2 what's its effect on combined connection?_

Out of five consecutive TCP connections, the first 3 will be routed over connection 1 and the next 2 over the second.

> _what's its difference with 1 ratio for each connection?_

A ration of 1 implies all internet connections are equal with no routing preference. The load will be evenly distributed. Useful when all of your Internet connections are of similar type.
