### ISSUE TITLE
Provide a statically linked MIPS Binary please!

### ISSUE THREAD

**Issue by Spamm00r** [extremecoders-re/go-dispatch-proxy#25]
Hi,

this is an awesome tool and solves a big problem. Thanks for this tool. I found it 5 minutes after I was searching for a solution to load balance two socks proxies.

I'm asking you to provide also a static MIPS binary. Unfortunately I lack the linux skill to crosscompile it myself.
MIPS is run on many Linux based routers and I'd like to run go-dispatch-proxy on my MIPS based router, which is running 24/7 and is handling all the internet anyway. So it would be handy to have a static MIPS binary on that router without having to run or configure another pc to use this app.

Thanks!

**Comment by extremecoders-re** [comment]
Cross compiling with go is really easy. Only a working go installation is needed. Go compiles statically by default.

## MIPS (big endian)
```
$ GOOS=linux GOARCH=mips go build -o go-dispatch-proxy.mips
```

## MIPSEL (little endian)

```
$ GOOS=linux GOARCH=mipsle go build -o go-dispatch-proxy.mipsle
```
Attached both builds. Compiled in clean environment on GitHub codespaces.
But you can always compile yourself by following the steps above.

[go-dispatch-proxy-mips-builds.zip](https://github.com/extremecoders-re/go-dispatch-proxy/files/9228942/go-dispatch-proxy-mips-builds.zip)

This is just the compiled binaries. Didn't try running though.

**Comment by Spamm00r** [comment]
Thanks for the binaries,

For the MIPSEL you misspelled it MIPSLE in your compilation command.

Also the MIPS version gives me "Illegal instruction" upon execution on my MIPS router.

**Comment by extremecoders-re** [comment]
Go refers to little endian mips as mipsle. Hence it is `GOARCH=mipsle`.
Technically mipsel is the same as mipsle.

About the illegal instruction error, perhaps you can upload an executable binary file from your router (/bin, /usr/bin etc) and I can cross-check the architecture the router supports.

**Comment by Spamm00r** [comment]
Here is a Wake on Lan Binary that works on the router.
[wol.zip](https://github.com/extremecoders-re/go-dispatch-proxy/files/9245739/wol.zip)

**Comment by extremecoders-re** [comment]
This has been compiled with soft floating point. The earlier build was hard float.

[go-dispatch-proxy-softfloat.zip](https://github.com/extremecoders-re/go-dispatch-proxy/files/9258054/go-dispatch-proxy-softfloat.zip)

**Comment by Spamm00r** [comment]
Yeah that works! It gives me proper response. 
I will test it in depth in the coming days with an aim to use it as my main load balancer.

Thanks!
