### ISSUE TITLE
Doesn't work on windows anymore

### ISSUE THREAD

**Issue by felixgouin** [extremecoders-re/go-dispatch-proxy#3]
[https://i.imgur.com/ZktjvQV.png](https://i.imgur.com/ZktjvQV.png)

**Comment by extremecoders-re** [comment]
Check the SOCKS version in the app you are using.  Go-dispatch-proxy only supports SOCKS v5.

For example, in Firefox  you can specify SOCKS v5 in Connection Settings.

![image](https://user-images.githubusercontent.com/12072382/81434788-5d955600-9184-11ea-928c-453901902bb3.png)

**Comment by felixgouin** [comment]
Ok thank you !
