### ISSUE TITLE
Add auto-DNS support in tunnel.

### ISSUE THREAD

**Issue by 0400H** [extremecoders-re/go-dispatch-proxy#34]
Version: v6

Not supported DNS currently, for example `proxy1.com` and `proxy2.com`.
CMD:

```
go-dispatch-proxy.exe -lhost 127.0.0.1 -lport 5566 -tunnel proxy1.com:1234 proxy2.com:1234
```

User need to find ip of domain name.

Could you add auto-DNS support?

**Comment by extremecoders-re** [comment]
This has been implemented in latest build.
