### ISSUE TITLE
How to launch it on Mac OS

### ISSUE THREAD

**Issue by alexisjamet** [extremecoders-re/go-dispatch-proxy#4]
Hello,

I don't know how to use it on Mac os... could you please give us clear instructions to run it on mac?

best,
Alexis ;)

**Comment by extremecoders-re** [comment]
I haven't tested it on mac but you should be able to run it from a terminal. Compatibility with mac is mentioned as a user reported it to be working.

**Comment by alexisjamet** [comment]
ok thanks but How to execute/launch it from my terminal? thank you in advance

**Comment by alexisjamet** [comment]
thanks
