### ISSUE TITLE
Great little tool

### ISSUE THREAD

**Issue by gregor-hh** [extremecoders-re/go-dispatch-proxy#5]
What a great little tool, it works well on Windows.

But I have a feature Request: 

May it be possible that the tool use another two „parent socks“ instead of interfaces?

I have 2 SSH Tunnels with SOCKS over 2 WAN interfaces (each SSH Tunnel on one Interface) 

I need to loadbalance theese.

Is this possbile?

**Comment by extremecoders-re** [comment]
This is possible but would require a refactor. Like instead of handling the SOCKS connection, forward it to the upstream.

Also I think this is natively supported in HAProxy.

**Comment by gregor-hh** [comment]
Unfortunately it has to run on windows.

Your tool is nice, small and needs few resources.

would be perfect if it could optionally use other socks instead of interfaces (load balanced)

Would that be a lot of extra code?

I mean, could you imagine building that or is it too much work?

best regards

**Comment by extremecoders-re** [comment]
Not too much work. In fact it would be easier as there's no need to handle socks. Need to just pipe the sockets.

Not sure when I'll be able to get time to implement this but you can give it a shot if you're versed with Go. As an example you can consider the second example here: https://www.stavros.io/posts/proxying-two-connections-go/

**Comment by extremecoders-re** [comment]
This has been implemented in the latest release.

**Comment by gregor-hh** [comment]
Awesome, you integrated it and it works perfect.

So Great! Many thanks to you, Iam very happy now.

Best regards
