### ISSUE TITLE
Implement SO_BINDTODEVICE

### ISSUE THREAD

**Issue by Magissia** [extremecoders-re/go-dispatch-proxy#6]
Hello, would be nice if it was possible to implement SO_BINDTODEVICE for full linux compatibility.

For various reasons, Go is preferred over nodejs for low power MIPS based devices and your tool happens to compile and run without errors in it's current state on MIPS.

**Comment by extremecoders-re** [comment]
This feature is definitely on the TODO list. Didn't get the time to work on this yet.

Meanwhile, it's always possible to manually set up the routing tables based on source IP and go-dispatch-proxy should work as expected.

- https://superuser.com/questions/376667/how-to-route-only-specific-subnet-source-ip-to-a-particular-interface
- https://serverfault.com/questions/642805/how-to-forward-traffic-to-different-nics-based-on-source

**Comment by extremecoders-re** [comment]
This has been implemented in the latest version.
