### ISSUE TITLE
Problem with windows 10 ver. 20H2

### ISSUE THREAD

**Issue by StefanoNiccolini** [extremecoders-re/go-dispatch-proxy#7]
Hi, this is my problem.

go-dispatch-proxy.exe -list
--- Listing the available adresses for dispatching
[+] Ethernet 2, IPv4:192.168.1.101
[+] Wi-Fi 2, IPv4:192.168.43.232

go-dispatch-proxy.exe 192.168.1.101@1 192.168.43.232@3

C:\APPOGGIO\AA>go-dispatch-proxy.exe 192.168.1.101@1 192.168.43.232@3
[INFO] Load balancer 1: 192.168.1.101, contention ratio: 1
[INFO] Load balancer 2: 192.168.43.232, contention ratio: 3
[INFO] Local server started on  127.0.0.1:8080

After setting windows 10 vers. 20H2 to use proxy ...
![Immagine](https://user-images.githubusercontent.com/79508375/108823989-765ee300-75c1-11eb-9a38-cc58a36ac503.jpg)
This error message appears:
[WARN] unsupported SOCKS version
[WARN] unsupported SOCKS version
[WARN] unsupported SOCKS version
.....
Any suggestions ?
Thank you

**Comment by extremecoders-re** [comment]
Windows uses the SOCKS5 protocol which is compatible with go-dispatch-proxy. The error looks to be due to some other application which is trying to use the SOCKS4 protocol.

**Comment by StefanoNiccolini** [comment]
Thanks for your answer.
Indeed, this was certainly the problem.
I say "was" as I found a Chrome extension on the Internet that allows
to set the SOCKS (4 or 5), as in FireFox.
In the standard settings of Chrome this is not possible or in any case I could not find this setting.
ONCE THIS IS DONE EVERYTHING WORKS WELL and the error message has disappeared.
The extension for Chrome is PROXY HELPER:
- https://chrome.google.com/webstore/detail/proxy-helper/mnloefcpaepkpmhaoipjkpikbnkmbnic
- https://github.com/henices/Chrome-proxy-helper
This is the setup screen.
![Immagine 2021-02-28 060003](https://user-images.githubusercontent.com/79508375/109408647-a32d4480-798b-11eb-95eb-f86c54b63c5a.png)

**Comment by extremecoders-re** [comment]
Good to know that!

**Comment by StefanoNiccolini** [comment]
HELLO.
OK THE PROBLEM IS SOLVED.
I apologize if I have directly exposed the problem without introducing myself.
I DO IT NOW.
I AM STEFANO NICCOLINI, CIVIL ENGINEER, AND I LIVE NEARBY
TO THE CITY OF ANCONA IN ITALY.
ALSO I HAVE TO THANK YOU FOR THE UTILITY YOU DEVELOPED BECAUSE
IT WILL BE VERY USEFUL TO MANAGE BETTER MY INTERNET CONNECTION 
THAT, LIVING IN THE COUNTRYSIDE, IS NOT THE BEST.
CURRENTLY I HAVE TWO LINES AVAILABLE: ONE ADSL UP TO 20 MBit/sec
(4-5 MBit/sec real) AND A WIFI ROUTER ON A MOBILE PHONE
(6-10 MBit/sec variable during the day).
IN ADDITION TO PERSONAL THANKS, I WOULD LIKE TO CONTRIBUTE TO SUPPORT THE
YOUR WORK THROUGH A DONATION, AS I HAVE DONE OTHER TIMES WITH
FREE SOFTWARE DEVELOPED AND MADE AVAILABLE TO OTHER GRARES
TO THE GOOD WILL AND ABILITY OF SOMEONE (or of many).
GREETINGS,
STEFANO NICCOLINI

**Comment by extremecoders-re** [comment]
@StefanoNiccolini I've added a sponsor button to the repository. Thanks for your support!
